添加 splash 模块，及相关说明文档
Passkou/bilibili_api pull request #111
Opened 2021-01-26 10:21 UTC by david082321

2021-01-28 13:40 UTC, Passkou requested changes
代码经测试没问题，但是看上去这是app的API，所以模块名用“app”更好理解。
原谅我英语水平，我查单词“splash”也没看懂是什么意思。。。个人认为开屏启动动画用“get_loading_images”更加通俗易懂。
另外，根据你的注释，一个是获取新版的开屏启动动画，另一个好像是旧版的，所以分别用"get_loading_images_old"和"get_loading_images"命名比较好

2021-01-28 13:40 UTC, Passkou commented on bilibili_api/splash.py
> +    :param birth: 生日日期
加个例子，这样不好理解

2021-01-28 13:40 UTC, Passkou commented on bilibili_api/splash.py
> +    :param ts: 当前UNIX秒
既然ts是当前时间戳，那直接用程序生成，无需用户传入不是更好吗

2021-01-29 10:18 UTC, david082321 commented
> 代码经测试没问题，但是看上去这是app的API，所以模块名用“app”更好理解。
> 原谅我英语水平，我查单词“splash”也没看懂是什么意思。。。个人认为开屏启动动画用“get_loading_images”更加通俗易懂。
> 另外，根据你的注释，一个是获取新版的开屏启动动画，另一个好像是旧版的，所以分别用"get_loading_images_old"和"get_loading_images"命名比较好

其实还有一个是更旧的，但是已弃用。
现在 list 是发普通的图（[参考这里(TG)](https://t.me/s/bilibili_splash)），brand 那个是发特殊节日的图。

2021-01-29 10:18 UTC, david082321 commented on bilibili_api/splash.py
> +def get_splash_bread(mobi_app: str = "android", platform: str = "android",
好的

2021-01-29 10:42 UTC, Passkou commented
也可以

2021-01-29 11:05 UTC, david082321 commented
> 也可以

改好了

2021-01-29 11:10 UTC, merged

2021-01-29 11:12 UTC, Passkou commented
另外注意一下，下次还要发pr的话向develop分支发起，主分支从 master 改到 main了，感谢贡献

2021-01-29 11:15 UTC, david082321 commented on bilibili_api/splash.py
> +    :param birth: 生日日期
> 另外注意一下，下次还要发pr的话向develop分支发起，主分支从 master 改到 main了，感谢贡献

收到，谢谢大佬。

2021-01-29 11:15 UTC, david082321 commented
> 另外注意一下，下次还要发pr的话向develop分支发起，主分支从 master 改到 main了，感谢贡献

收到，谢谢大佬。