增加获取房间播放信息及直播流列表v2
Passkou/bilibili_api pull request #89
Opened 2020-12-17 16:40 UTC by ATKghost

2020-12-18 12:09 UTC, Passkou requested changes
看样子是新的api，改了这几个地方基本就没问题了

2020-12-18 12:09 UTC, Passkou commented on bilibili_api/data/api.json
> +          "protocol": "0,1",
经测试该处只有为1时才有可用清晰度，所以只写成1就行

2020-12-18 12:09 UTC, Passkou commented on bilibili_api/data/api.json
> +          "format": "0,2",
同上，为2

2020-12-18 12:09 UTC, Passkou commented on bilibili_api/data/api.json
> +          "codec": "0,1",
这里为0或1都可以，直接随便写一个吧

2020-12-18 12:09 UTC, Passkou commented on bilibili_api/data/api.json
> +        "comment": "获取房间播放信息及直播流列表v2"
改为：获取房间信息及可用清晰度列表

2020-12-29 18:14 UTC, ATKghost commented on bilibili_api/data/api.json
> +          "protocol": "0,1",
试了下，0是FLV流，1是HLS流
参考.data.playurl_info.playurl.stream[0].protocol_name

2020-12-29 18:14 UTC, ATKghost commented on bilibili_api/data/api.json
> +          "format": "0,2",
同理，
0是flv格式
1是ts格式，仅限hls流
2是fmp4格式，仅限hls流
参考.data.playurl_info.playurl.stream[0].format[0].format_name

2020-12-29 18:14 UTC, ATKghost commented on bilibili_api/data/api.json
> +          "codec": "0,1",
0是avc编码
1是hevc编码，目前还没发现有实装的
参考.data.playurl_info.playurl.stream[0].format[0].codec[0].codec_name

2020-12-30 02:01 UTC, merged